bread_posttrain:
  dataset_names:
  - bread

  data_config_names:
  - "bread"

  embodiment_tags:
  - "new_embodiment"

  sampling_strategy: "step"
  video_backend: "torchvision_av"

  vit_transform_args:
    type: "beingh"
    normalize_type: "imagenet"
    use_color_jitter: false

  frame_step_size:
  - 1

  num_used_episodes_per_task:
  - -1

  num_used_episodes_per_dataset:
  - -1

  num_used_frames_per_dataset:
  - 128

  weight: 1
